package com.example.fresaproyecto.interfaces

interface IComunicaFragments {
    fun menuCultivo()
    fun menuPersonal()
    fun regCultivo()
    fun regJornal()
    fun regCosecha()
    fun regInsumos()
    fun inicio()
    fun gestionarCultivo()
    fun gestionarPersona()
    fun regGastos()
    fun regIngresos()
    fun resultadoMensual()
    fun resultadoMensualCultivo()
    fun regPersona()
    fun presentacionApp()
    fun actPersona()
    fun actCultivo()
    fun actJornal()
    fun actInsumo()
    fun actCosecha()
    fun actGasto()
    fun actIngreso()
}